import { makePdf } from "./pdf";
import { COMPANY, type AO } from "./seed";
import { bpdeTotals, type Dossier } from "./store";
import { enLettres, fdate, money } from "./format";

export async function genDoc(kind: string, d: Dossier, ao: AO, extra: { staff?: { nom: string; poste: string; diplome: string; experience: number }[]; equip?: { nom: string; qte: number; etat: string }[]; refs?: { projet: string; mo: string; nature: string; montant: number; annee: number }[] } = {}, preview = false) {
  const t = bpdeTotals(d);
  const draft = !d.validations.includes("Direction");
  const ident = `${COMPANY.raison}, ${COMPANY.forme}, ICE ${COMPANY.ice}, ${COMPANY.rc}, ${COMPANY.if}, ${COMPANY.cnss}, dont le siège est ${COMPANY.adresse}, représentée par ${COMPANY.representant}, en qualité de ${COMPANY.qualite}.`;
  const objet = `Objet : ${ao.objet} — ${ao.ref} — Maître d'ouvrage : ${ao.mo}`;
  const fait = `Fait à Casablanca, le ${fdate(new Date())}\n\nSignature et cachet : ____________________`;
  const fname = (p: string) => `AO-${ao.ref.replace(/[^\w]+/g, "-")}_${d.id}_${p}.pdf`;
  switch (kind) {
    case "Déclaration sur l'honneur":
      return makePdf("Déclaration sur l'honneur", [{ paragraphs: [objet, `Je soussigné, ${COMPANY.representant}, agissant au nom et pour le compte de ${ident}`, "1. Déclare remplir les conditions prévues par le dossier d'appel d'offres et par la réglementation des marchés publics (Décret n° 2-22-431).", "2. Atteste que la société est en situation fiscale et sociale régulière (DGI, CNSS).", "3. Atteste que la société n'est ni en liquidation judiciaire ni en redressement judiciaire.", "4. Certifie l'exactitude des renseignements contenus dans la présente déclaration et dans les pièces fournies.", "5. M'engage à ne pas recourir, par moi-même ou par personne interposée, à des actes de corruption ou de fraude, ni à des pratiques de collusion.", "6. M'engage à respecter la confidentialité des informations portées à ma connaissance.", fait] }], { draft, filename: fname("declaration-honneur"), preview, subtitle: "Modèle du dossier d'appel d'offres" });
    case "Acte d'engagement":
      return makePdf("Acte d'engagement", [{ paragraphs: [objet, `Je soussigné, ${COMPANY.representant}, agissant au nom et pour le compte de ${ident}`, `Après avoir pris connaissance du dossier d'appel d'offres, je m'engage à exécuter les prestations conformément au CPS, moyennant les prix établis au bordereau des prix – détail estimatif, pour un montant de :`, `Montant HT : ${money(t.ht)}\nTVA 20 % : ${money(t.tva)}\nMontant TTC : ${money(d.acteMontant ?? t.ttc)}`, `Arrêté en lettres à la somme de : ${enLettres(d.acteMontant ?? t.ttc)} TTC.`, `Délai d'exécution : ${ao.delaiExec}.`, `L'administration se libérera des sommes dues en faisant donner crédit au compte : ${COMPANY.rib}.`, fait] }], { draft, filename: fname("acte-engagement"), preview });
    case "BPDE":
      return makePdf("Bordereau des prix – détail estimatif", [{ paragraphs: [objet] }, { table: { head: ["N°", "Désignation", "Unité", "Qté", "PU HT", "Total HT"], rows: d.bpde.map((l) => [l.num, l.designation, l.unite, l.qte, money(l.pu), money(l.qte * l.pu)]) } }, { paragraphs: [`Total de base HT : ${money(t.base)} · Coefficients : marge ${d.coefs.marge} %, déplacement ${d.coefs.depl} %, aléas ${d.coefs.aleas} %, remise ${d.coefs.remise} %`, `Total HT : ${money(t.ht)}\nTVA 20 % : ${money(t.tva)}\nTotal TTC : ${money(t.ttc)}`, `Arrêté le présent bordereau à la somme de : ${enLettres(t.ttc)} TTC.`, fait] }], { draft, filename: fname("BPDE"), preview });
    case "Note moyens humains & techniques":
      return makePdf("Note sur les moyens humains et techniques", [{ paragraphs: [objet, `Pour la réalisation de la prestation « ${ao.objet} », LGTP mobilise les moyens suivants depuis son agence la plus proche.`] }, { title: "Moyens humains", table: { head: ["Nom", "Poste", "Diplôme", "Expérience"], rows: (extra.staff ?? []).map((p) => [p.nom, p.poste, p.diplome, `${p.experience} ans`]) } }, { title: "Moyens techniques", table: { head: ["Équipement", "Quantité", "État"], rows: (extra.equip ?? []).map((e) => [e.nom, e.qte, e.etat]) } }], { draft, filename: fname("note-moyens"), preview });
    case "Mémoire méthodologique + planning":
      return makePdf("Mémoire méthodologique et planning", [{ paragraphs: [objet, "1. Compréhension de la mission et contexte géologique du site.", "2. Programme de reconnaissance : sondages carottés, essais pénétrométriques, essais pressiométriques, prélèvements et essais de laboratoire.", "3. Organisation : chef de mission, ingénieur géotechnicien, équipe de sondage, laboratoire.", "4. Plan d'assurance qualité et sécurité (EPI, balisage, réseaux enterrés)."] }, { title: "Planning (Gantt simplifié)", table: { head: ["Tâche", "S1", "S2", "S3", "S4", "S5", "S6"], rows: [["Mobilisation", "■", "", "", "", "", ""], ["Sondages & essais in situ", "■", "■", "■", "", "", ""], ["Essais de laboratoire", "", "■", "■", "■", "", ""], ["Rapport géotechnique", "", "", "", "■", "■", ""], ["Remise du rapport final", "", "", "", "", "", "■"]] } }], { draft, filename: fname("memoire"), preview });
    case "Lettre de demande de caution":
      return makePdf("Demande de caution provisoire", [{ paragraphs: ["À l'attention de : Attijariwafa bank — Service des engagements par signature", objet, `Madame, Monsieur, nous vous prions de bien vouloir émettre une caution provisoire personnelle et solidaire d'un montant de ${money(ao.caution)} (${enLettres(ao.caution)}) au profit de ${ao.mo}, relative à l'appel d'offres ${ao.ref}, valable au minimum 75 jours à compter de la date limite de dépôt (${fdate(ao.deadline)}).`, "Veuillez agréer nos salutations distinguées.", fait] }], { filename: fname("demande-caution"), preview });
    case "Liste des références":
      return makePdf("Liste des références", [{ paragraphs: [objet] }, { table: { head: ["Projet", "Maître d'ouvrage", "Nature", "Montant", "Année"], rows: (extra.refs ?? []).map((r) => [r.projet, r.mo, r.nature, money(r.montant, 0), r.annee]) } }], { draft, filename: fname("references"), preview });
    default:
      return makePdf("Bordereau de remise des pièces", [{ paragraphs: [objet] }, { table: { head: ["Section", "Pièce", "Statut"], rows: d.checklist.map((p) => [p.section, p.libelle, p.statut]) } }], { draft, filename: fname("bordereau"), preview });
  }
}
